# Generated by Django 5.1.6 on 2025-03-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text='Imię lub imiona współtwórcy.', max_length=50)),
                ('last_names', models.CharField(help_text='Nazwisko lub nazwiska współtwórcy.', max_length=50)),
                ('email', models.EmailField(help_text='E-mail współtwórcy.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł książki.', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Data publikacji książki.')),
                ('isbn', models.CharField(max_length=20, verbose_name='Numer ISBN książki.')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='Rola, jaką współtwórca odegrał podczas tworzenia tej książki.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='reviews.BookContributor', to='reviews.contributor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Tekst recenzji.')),
                ('rating', models.IntegerField(help_text='Ocena uzytkownika.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia recenzji.')),
                ('date_edited', models.DateTimeField(help_text='Data i czas ostatniej edycji recenzji.', null=True)),
                ('book', models.ForeignKey(help_text='Recenzowana książka.', on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
